# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: golive-Azure
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        resourceGroupName="cloud-shell-storage-westus"
        storageAccountName="cs4743f6ed683a8x46f0x822"

        # This command assumes you have logged in with az login
        httpEndpoint=$(az storage account show \
            --resource-group $resourceGroupName \
            --name $storageAccountName \
            --query "primaryEndpoints.file" | tr -d '"')
        smbPath=$(echo $httpEndpoint | cut -c7-$(expr length $httpEndpoint))
        fileHost=$(echo $smbPath | tr -d "/")

        nc -zvw3 $fileHost 445

        # create a share folder for the mount point
        fileShareName="tfstate"
        mntPath="/mnt/$storageAccountName/$fileShareName"
        sudo mkdir -p $mntPath

        storageAccountKey=$(az storage account keys list \
            --resource-group $resourceGroupName \
            --account-name $storageAccountName \
            --query "[0].value" | tr -d '"')

        sudo mount -t cifs $smbPath $mntPath -o vers=3.0,username=$storageAccountName,password=$storageAccountKey,serverino
